package com.rubyhuntersky.chain

const val MINUTES_PER_HOUR = 60
const val HOURS_PER_DAY = 24
const val DAYS_PER_MONTH = 30
const val MINUTES_PER_MONTH = MINUTES_PER_HOUR * HOURS_PER_DAY * DAYS_PER_MONTH


const val TARGET_MINUTES_BETWEEN_BLOCKS = 5
const val TARGET_BLOCKS_PER_MINUTE = 1.0 / TARGET_MINUTES_BETWEEN_BLOCKS

const val TARGET_MONTHS_PER_INK_WELL = 6
const val INK_DWELL_LENGTH = (TARGET_BLOCKS_PER_MINUTE * MINUTES_PER_MONTH * TARGET_MONTHS_PER_INK_WELL).toLong()
